spring:
  application:
    name: dev_error
  datasource:
    url: jdbc:mysql://localhost:6657/common_mistakes?characterEncoding=UTF-8&useSSL=false&rewriteBatchedStatements=true
    username: root
    password: kIo9u7Oi0eg
    platform: mysql
    maximum-pool-size: 100
  spring.jpa.open-in-view=false
ribbon:
  ReadTimeout: 4000
  ConnectTimeout: 4000
server:
  port: 7888
  servlet:
    encoding:
      force: true
      charset: UTF-8
