/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
class Library {
    def someLibraryMethod() {
        true
    }

    static void main(String[] args) {
        def a = new Library()
        print a.someLibraryMethod()
        def multiline ='''line1
               line2
               line3
        '''
        println multiline
        def ranga = 1..<5
        print ranga.to
    }
}
